# Note, This template deploys an Application Load Balancer that exposes our PHP APP services.
# Service : PHP-fpm Service listen to port 9000
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys an Application Load Balancer that exposes our PHP APP services.

Parameters:
  PMServerEnv:
    Description: "Server Environment name."
    ConstraintDescription: "Choose an Environment from the drop down"
    Type: "String"
    AllowedValues:
      - "dev"
      - "staging"
      - "prod"
  PMVPC:
    Description: "VPC to launch instances into"
    Type: "AWS::EC2::VPC::Id"

  PMAPPALBSG:
    Description: "Select the Security Group to use for the ALB"
    Type: "AWS::EC2::SecurityGroup::Id"

  PMPublicSubnets:
    Description: "Subnets to launch instances into"
    Type: "List<AWS::EC2::Subnet::Id>"

  # PMS3Logging:
  #   Description: "S3 Logging Bucket Name"
  #   Type: "String"


####### Resources Setup #######
Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 4
      Matcher:
        HttpCode: '200'
      Name: !Sub "${PMServerEnv}-AppAlbTargets"
      Port: 80
      Protocol: HTTP
      VpcId: !Ref "PMVPC"
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${PMServerEnv}-AppALB"
      Scheme: internet-facing
      Subnets: !Ref "PMPublicSubnets"
      SecurityGroups:
        - Ref: "PMAPPALBSG"
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: TargetGroup
      LoadBalancerArn:
          Ref: ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

# Output LoadBalancer
Outputs:
  APPLoadBalancer:
    Description: "A reference to the Application Load Balancer"
    Value: !Ref "ApplicationLoadBalancer"

  APPLoadBalancerUrl:
    Description: "The URL of the ALB"
    Value: !GetAtt "ApplicationLoadBalancer.DNSName"

  rTargetGroup:
    Description: "The resukt of TargetGroup"
    Value: !Ref "TargetGroup"