# Note, This template deploys a Webserver Load Balancer that exposes our Nginx Proxy/Apache http services.
# Service : Nginx Service listen to port 80
# SSL Termination is at ELB
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys an Webserver Load Balancer that exposes our Nginx Proxy services.

Parameters:

  PMServerEnv:
    Description: "Server Environment name."
    ConstraintDescription: "Choose an Environment from the drop down"
    Type: "String"
    AllowedValues:
      - "dev"
      - "staging"
      - "prod"
  PMVPC:
    Description: "VPC to launch instances into"
    Type: "AWS::EC2::VPC::Id"

  PMAPPELBSG:
    Description: "Select the Security Group to use for the ELB"
    Type: "AWS::EC2::SecurityGroup::Id"

  PMPrivateSubnets:
    Description: "Subnets to launch instances into"
    Type: "List<AWS::EC2::Subnet::Id>"

  # PMS3Backup:
  #   Description: "S3 Backup Bucket Name"
  #   Type: "String"

  # PMS3Logging:
  #   Description: "S3 Logging Bucket Name"
  #   Type: "String"

  # PMDomain1CertARN:
  #   Description: "ARN for Demo domain name"
  #   Type: "String"

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 4
      Matcher:
        HttpCode: '200'
      Name: !Sub "${PMServerEnv}-WebAlbTargets"
      Port: 80
      Protocol: HTTP
      VpcId: !Ref "PMVPC"
  WebLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${PMServerEnv}-WebALB"
      Scheme: internet-facing
      Subnets: !Ref "PMPrivateSubnets"
      SecurityGroups:
        - Ref: "PMAPPELBSG"
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: TargetGroup
      LoadBalancerArn:
          Ref: WebLoadBalancer
      Port: 80
      Protocol: HTTP

# Output LoadBalancer
Outputs:
  WEBLoadBalancer:
    Description: "A reference to the Web Load Balancer"
    Value: !Ref "WebLoadBalancer"

  WEBLBDNSName:
    Description: "The URL of the Web Load Balancer"
    Value: !GetAtt "WebLoadBalancer.DNSName"

  # WEBLBHostedZoneId:
  #   Description: "The CanonicalHostedZoneNameID of the Web Load Balancer"
  #   Value: !GetAtt "WebLoadBalancer.CanonicalHostedZoneNameID"

  rTargetGroup:
    Description: "The resukt of TargetGroup"
    Value: !Ref "TargetGroup"